sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker
before_install:
  - docker build -t arian/devops-my-gatsby-site -f Dockerfile.dev .
script:
  - docker run -e CI=true arian/devops-my-gatsby-site npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" ### AWS region of your choice
  app: "devops-my-gatsby-site" ### Your EB App name
  env: "devopsmygatsbysite-test-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-us-east-1-536501238579" ### S3 bucket name
  bucket_path: "mygatsby" ### S3 folder name under S3 bucket above
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
